<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pinnacle_line_feed [
<!ELEMENT PinnacleFeedTime (#PCDATA)>
<!ELEMENT lastContest (#PCDATA)>
<!ELEMENT lastGame (#PCDATA)>
<!ELEMENT contest_maximum (#PCDATA)>
<!ELEMENT contestantnum (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT event (event_datetimeGMT, gamenumber, sporttype, league,IsLive?, contest_maximum?, description?, (participants |  periods | total)+)>
<!ELEMENT event_datetimeGMT (#PCDATA)>
<!ELEMENT gamenumber (#PCDATA)>
<!ELEMENT league (#PCDATA)>
<!ELEMENT odds (moneyline_value, to_base?)>
<!ELEMENT over_adjust (#PCDATA)>
<!ELEMENT participants (participant*)>
<!ELEMENT participant (participant_name, contestantnum, rotnum, visiting_home_draw?, odds?, pitcher?)>
<!ELEMENT participant_name (#PCDATA)>
<!ELEMENT periods (period*)>
<!ELEMENT period (period_number, period_description, periodcutoff_datetimeGMT, period_status, period_update, spread_maximum?, moneyline_maximum?, total_maximum?, moneyline?, spread?, total?)>
<!ELEMENT period_number (#PCDATA)>
<!ELEMENT period_description (#PCDATA)>
<!ELEMENT period_status (#PCDATA)>
<!ELEMENT period_update (#PCDATA)>
<!ELEMENT periodcutoff_datetimeGMT (#PCDATA)>
<!ELEMENT pinnacle_line_feed (PinnacleFeedTime, lastContest, lastGame, events)>
<!ELEMENT events (event*)>
<!ELEMENT pitcher (#PCDATA)>
<!ELEMENT rotnum (#PCDATA)>
<!ELEMENT sporttype (#PCDATA)>
<!ELEMENT moneyline (moneyline_visiting, moneyline_home, moneyline_draw?)>
<!ELEMENT moneyline_value (#PCDATA)>
<!ELEMENT moneyline_visiting (#PCDATA)>
<!ELEMENT moneyline_home (#PCDATA)>
<!ELEMENT moneyline_draw (#PCDATA)>
<!ELEMENT moneyline_maximum (#PCDATA)>
<!ELEMENT spread (spread_visiting, spread_adjust_visiting, spread_home, spread_adjust_home)>
<!ELEMENT spread_adjust_home (#PCDATA)>
<!ELEMENT spread_adjust_visiting (#PCDATA)>
<!ELEMENT spread_home (#PCDATA)>
<!ELEMENT spread_maximum (#PCDATA)>
<!ELEMENT spread_visiting (#PCDATA)>
<!ELEMENT to_base (#PCDATA)>
<!ELEMENT total (total_points, over_adjust?, under_adjust?, units?)>
<!ELEMENT total_maximum (#PCDATA)>
<!ELEMENT total_points (#PCDATA)>
<!ELEMENT under_adjust (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT IsLive (#PCDATA)>
<!ELEMENT visiting_home_draw (#PCDATA)>
]>

<pinnacle_line_feed>
	<PinnacleFeedTime>1400685305390</PinnacleFeedTime>
	<lastContest>23034237</lastContest>
	<lastGame>134568183</lastGame>
	<events>
		<event>
			<event_datetimeGMT>2014-05-21 15:30</event_datetimeGMT>
			<gamenumber>376565932</gamenumber>
			<sporttype>Tennis</sporttype>
			<league>Dusseldor 16</league>
			<IsLive>No</IsLive>
			<participants>
				<participant>
					<participant_name>Andreas Seppi</participant_name>
					<contestantnum>8237</contestantnum>
					<rotnum>8237</rotnum>
					<visiting_home_draw>Visiting</visiting_home_draw>
				</participant>
				<participant>
					<participant_name>Adrian Mannarino</participant_name>
					<contestantnum>8238</contestantnum>
					<rotnum>8238</rotnum>
					<visiting_home_draw>Home</visiting_home_draw>
				</participant>
			</participants>
			<periods>
				<period>
					<period_number>0</period_number>
					<period_description>Match</period_description>
					<periodcutoff_datetimeGMT>2014-05-21 15:30</periodcutoff_datetimeGMT>
					<period_status>O</period_status>
					<period_update>open</period_update>
					<spread_maximum>2500</spread_maximum>
					<moneyline_maximum>2500</moneyline_maximum>
					<total_maximum>1250</total_maximum>
					<moneyline>
						<moneyline_visiting>-371</moneyline_visiting>
						<moneyline_home>322</moneyline_home>
					</moneyline>
					<spread>
						<spread_visiting>-4.5</spread_visiting>
						<spread_adjust_visiting>-106</spread_adjust_visiting>
						<spread_home>4.5</spread_home>
						<spread_adjust_home>-106</spread_adjust_home>
					</spread>
					<total>
						<total_points>20.5</total_points>
						<over_adjust>-108</over_adjust>
						<under_adjust>-104</under_adjust>
					</total>
				</period>
			</periods>
		</event>
	</events>
</pinnacle_line_feed>
